### ISSUE TITLE
Unexpected File Names in Testing Log

### ISSUE THREAD

**Issue by mdhchan** [HPCE/hpce-2017-cw2#51]
The following tests appear to have strangely named files:

- Test 25 has direct_fourier_transform_parfor.cpp
- Test 26 and 27 has direct_fourier_transform_combined.cpp

Should they be fast_fourier_transform_parfor.cpp and fast_fourier_transform_combined.cpp respectively?

**Comment by m8pple** [comment]
It's a typo in the message, so yes, it doesn't quite match what the test is doing.
However, the themselves tests are testing the right files.

If you look at what it prints in the detailed log, it is trying to do:
````
(cd $WORKING_DIR/src && g++ -std=c++11 -E -I ../include $SL/fast_fourier_transform_parfor.cpp -o -) \ | $SCRIPTS_DIR/extract_preprocessed_part.pl $SL/fast_fourier_transform_parfor.cpp \ | grep parallel_for -
g++: error: login/fast_fourier_transform_parfor.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
login, 25, Checking direct_fourier_transform_parfor.cpp uses parallel_for at some point., FAIL
````
So yes, the message should indeed refer `fast_fourier_transform_parfor.cpp`, as that is what
the test is looking at. So that means you're correct, the files _actually_ being looked at are:

- 25 : fast_fourier_transform_parfor.cpp
- 26 : fast_fourier_transform_combined.cpp
- 27 : fast_fourier_transform_combined.cpp

Where possible the messages are derived from the tests themselves, but sometimes they
have to be done separately. This test script is a few years old, but I don't think anyone
has ever noticed the discrepancy before - thanks, I'll update it.
