### ISSUE TITLE
Standard output not allowed?

### ISSUE THREAD

**Issue by jeg114** [HPCE/hpce-2017-cw2#59]
I am seeing some failed tests where the conditions passed but the testing script seems to not like standard output I have included for debug purposes (tracking the K values are correctly set) as can be seen in the log.

```
user = 3.048, time=0.773015
echo parallelism = REC_K set to: 2 LOOP_K set to: 5 3.9429999870
(standard_in) 1: illegal character: R
(standard_in) 1: illegal character: _
(standard_in) 1: illegal character: K
(standard_in) 1: syntax error
(standard_in) 1: illegal character: :
(standard_in) 1: illegal character: L
(standard_in) 1: illegal character: O
(standard_in) 1: illegal character: O
(standard_in) 1: illegal character: P
(standard_in) 1: illegal character: _
(standard_in) 1: illegal character: K
(standard_in) 1: illegal character: :
jeg114, 35, Timing hpce.jeg114.fast_fourier_transform_combined with 4 CPUs and n=2^20: check observed parallelism (totalTime/wallTime) of REC_K set to: 2 LOOP_K set to: 5 3.9429999870 is more than 2.5., FAIL
```
I don't recall any of the specs/lecturers forbidding standard output. I will change it to have to have debug explicitly enabled by define statement, but it would be good to know if regarding the tests standard output (or even error output) is allowed.

**Comment by m8pple** [comment]
Standard output (and input) is always owned by the person/user/thing who owns `main`.
In this case you are implementing library functions, and have no control over `main` - there
are two different mains already in the repository, and I'm using two alternatives for testing,
and your library functions have no idea which one is in effect.

So if you are implementing a library, then you should only print to `stdout` if either:
- The library API contract explicitly allows/requires you to print to stdout; or
- You are given a handle of some sort as a parameter, that just happens to represent stdout.

It's rarely stated explicitly, but this contract holds should true across all libraries,
especially in UNIX world where the primary means of input/output is via stdin/stdout.

It helps if you turn it around. Take these assumptions:

- You are writing a program, and you need to produce your output on `stdout` in a pre-agreed format.

- You need to use a library, but you don't know what/whether it will write to `stdout` when you call it.

Is it possible to use that library within your program?

Another way to view it is in terms of `stdin` as a mirror of `stdout`, which is something that
people occasionally get wrong as well. If your library _might_ call `getc`, is there any way
of using it within a program? Even if the program doesn't use `stdin`, the library might
still try to read from it, and block the whole program (this happens quite a lot in submissions).

However, if you look at what you're trying to do with your `printf`, you're not actually trying
to produce _output_, you're trying to produce debug or logging information. That is a very
different thing, and there is actually a route for that via `stderr`. So while it might be
considered a bit rude for a library to print on `stderr`, you're not breaking any contracts
(unless the library API explicitly says you _can't_ print on `stderr`), and it won't stop
the program working (though it may slow it down). Many libraries will provide a log level
or verbosity API function that allows you to select how much they print on `stderr`, with
the default usually being either nothing, or only fatal messages.

You might have noticed that (in my rather anachronistic C within C++ style) I tend to use
the rather verbose forms of:
````
fprintf(stderr, ...);
fprintf(stdout, ...);
````
and I usually don't use:
````
printf(...);
````
In part that is in order to force me to make a conscious decision about what kind of printing
it is that I'm doing - is it output, or is it logging?

**Comment by jeg114** [comment]
Thanks for the thorough explanation 👍
