### ISSUE TITLE
Test numbers seem to have doubled

### ISSUE THREAD

**Issue by DhruvArora96** [HPCE/hpce-2017-cw2#61]
I am at the end of section 3. After including the environment variables, I have re made the program and it has compiled successfully. However upon testing I have found that the number of tests has doubled from 37713 to 75162. I have made no other changes. I pass 37713 tests as shown in the image. 
![screenshottestfail](https://user-images.githubusercontent.com/25771571/31955436-4f4262c0-b8e0-11e7-9528-91733ae26457.png)

**Comment by m8pple** [comment]
The main problem from your point of view is that you're simply failing lots of tests,
as you can see from all the lines being printed. So they all represent cases where
your transform is broken. It is expecting to get something non-zero out, and
the transform is providing (0,0) out, so the transform isn't working.

This is obscured by a bug in the testing script, where it says:
````
Passed 37713 out of 75160 tests.
````
so it should be printing:
````
Passed $(passed) out of $(executed) tests.
````
but it looks like there is a long hidden (like years...) bug that no-one
noticed, so it is actually printing:
````
Passed $(executed) out of $(executed+failed) tests.
````
So for your implementation, that means you are failing 37449 out of 37713.

-

Interestingly, the bug is due to a misnamed variable called `s_totalPassed`, which
is actually tracking the total number of _executed_ tests. I think this has managed
to persist for so many years because:
- People look for the presence of error messages rather than the count to see whether it works (so it
   didn't bother students).
- The exit code for the program is based on the number of failed tests, so from an
   assessment point of view it is still accurate (so it didn't bother me).
